name: Delphi Code Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  code-scan:
    runs-on: [self-hosted, Windows, X64, Delphi-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile with Delphi MSBuild
        shell: powershell
        run: |
          $studioPath = "C:\Program Files (x86)\Embarcadero\Studio\22.0"
          $rsvarsPath = "$studioPath\bin\rsvars.bat"

          # Find .dproj file
          $dprojFile = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter *.dproj | Select-Object -First 1

          if (-not $dprojFile) {
            Write-Host "ERROR: No .dproj file found."
            exit 1
          }

          $dprojPath = $dprojFile.FullName
          Write-Host "Found .dproj: $dprojPath"

          if (-not (Test-Path $rsvarsPath)) {
            Write-Host "ERROR: rsvars.bat not found at $rsvarsPath"
            exit 1
          }

          # Use rsvars.bat to load Delphi environment and then run MSBuild
          $cmd = "`"$rsvarsPath`" && msbuild `"$dprojPath`" /p:Config=Release /p:Platform=Win32"
          cmd.exe /c $cmd

          Write-Host "Running Delphi MSBuild with rsvars.bat..."
          Invoke-Expression $cmd

          if ($LASTEXITCODE -ne 0) {
            Write-Host "ERROR: Delphi MSBuild failed with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }

          Write-Host "Compilation completed successfully!"

      - name: Run Pascal Analyzer (HTML + SARIF)
        run: |
          & "C:\Program Files\Peganza\Pascal Analyzer Eval 9\palcmd.exe" `
            /PROJECT="$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\Project1.dpr" `
            /OUTPUT="$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\analysis-output.html" `
            /SARIF="$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\results.sarif"

      - name: Upload HTML Report
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "$env:GITHUB_WORKSPACE\artifacts"
          if (Test-Path "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\analysis-output.html") {
            Copy-Item "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\analysis-output.html" "$env:GITHUB_WORKSPACE\artifacts\"
            Write-Host "HTML report saved to artifacts directory"
          } else {
            Write-Host "HTML report not found"
          }

      - name: Save SARIF Report
        shell: powershell
        run: |
          if (Test-Path "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\results.sarif") {
            Copy-Item "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\results.sarif" "$env:GITHUB_WORKSPACE\artifacts\"
            Write-Host "SARIF report saved to artifacts directory"
            Get-Content "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\results.sarif" | Write-Host
          } else {
            Write-Host "SARIF report not found"
          }
