name: Delphi Code Scan
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  code-scan:
    runs-on: [self-hosted, Windows, X64, Delphi-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile with Delphi MSBuild
        shell: powershell
        run: |
          $studioPath = "C:\Program Files (x86)\Embarcadero\Studio\22.0"
          $rsvarsPath = "$studioPath\bin\rsvars.bat"
          $dprojFile = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter *.dproj | Select-Object -First 1
          if (-not $dprojFile) { Write-Host "ERROR: No .dproj file found."; exit 1 }
          $dprojPath = $dprojFile.FullName
          Write-Host "Found .dproj: $dprojPath"
          if (-not (Test-Path $rsvarsPath)) { Write-Host "ERROR: rsvars.bat not found at $rsvarsPath"; exit 1 }
          $cmd = "`"$rsvarsPath`" && msbuild `"$dprojPath`" /p:Config=Release /p:Platform=Win32"
          Write-Host "Running Delphi MSBuild with rsvars.bat..."
          cmd.exe /c $cmd
          if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: Delphi MSBuild failed with exit code $LASTEXITCODE"; exit $LASTEXITCODE }
          Write-Host "Compilation completed successfully!"

      - name: Run Pascal Analyzer
        shell: powershell
        run: |
          $projectPath = "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\Project1.dpr"
          $palcmdPath = "C:\Program Files\Peganza\Pascal Analyzer Eval 9\palcmd.exe"
          $paOutputDir = "C:\Users\$env:USERNAME\Documents\Pascal Analyzer\Projects\Output\Project1"
          $warningsFile = "$paOutputDir\Warnings.txt"
          $bindingsFile = "$paOutputDir\Bindings.txt"
          $targetOutputDir = "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest"
          $targetWarningsFile = "$targetOutputDir\analysis-output.txt"

          if (-not (Test-Path $palcmdPath)) { Write-Host "ERROR: palcmd.exe not found at: $palcmdPath"; exit 1 }
          if (-not (Test-Path $targetOutputDir)) { New-Item -ItemType Directory -Force -Path $targetOutputDir }
          if (Test-Path $paOutputDir) {
            Write-Host "Cleaning up previous Pascal Analyzer output..."
            Remove-Item "$paOutputDir\*" -Force -ErrorAction SilentlyContinue
          }

          Write-Host "Running Pascal Analyzer..."
          & "$palcmdPath" "$projectPath"
          if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: Pascal Analyzer failed with exit code $LASTEXITCODE"; exit $LASTEXITCODE }

          if (Test-Path $warningsFile) {
            Copy-Item $warningsFile $targetWarningsFile
            $fileSize = (Get-Item $targetWarningsFile).Length
            Write-Host "Copied Warnings.txt to analysis-output.txt (Size: $fileSize bytes)"
            if ($fileSize -gt 0) {
              Write-Host "First few lines of warnings file:"
              Get-Content $targetWarningsFile -TotalCount 10 | ForEach-Object { Write-Host "  $_" }
            }
          } elseif (Test-Path $bindingsFile) {
            Copy-Item $bindingsFile $targetWarningsFile
            Write-Host "Copied Bindings.txt to analysis-output.txt as fallback"
          } else {
            $txtFiles = Get-ChildItem $paOutputDir -Filter "*.txt" -ErrorAction SilentlyContinue
            if ($txtFiles.Count -gt 0) {
              Copy-Item $txtFiles[0].FullName $targetWarningsFile
              Write-Host "Copied $($txtFiles[0].Name) to analysis-output.txt"
            } else {
              Write-Host "ERROR: No suitable output file found in Pascal Analyzer output directory"
              exit 1
            }
          }

      - name: Convert Pascal Analyzer output to SARIF
        shell: powershell
        run: |
          $modulePath = "C:\Program Files\WindowsPowerShell\Modules\ConvertToSARIF\1.0.0"
          $textOutputPath = "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\analysis-output.txt"
          $sarifOutputPath = "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\results.sarif"

          if (-not (Test-Path $textOutputPath)) {
            Write-Host "ERROR: Pascal Analyzer output file not found at: $textOutputPath"
            exit 1
          }

          if (-not (Test-Path "$modulePath\ConvertToSARIF.psd1")) {
            Write-Host "WARNING: ConvertToSARIF module not found. Using fallback SARIF generator"
            $lines = Get-Content $textOutputPath -ErrorAction SilentlyContinue
            $findings = @()
            foreach ($line in $lines) {
              # Adjust regex pattern as needed to match Pascal Analyzer output
              if ($line -match "^(.+?)\((\d+)\):\s*(.+)$") {
                $findings += @{
                  ruleId = "PascalAnalyzerFinding"
                  message = @{ text = $matches[3] }
                  locations = @(@{
                    physicalLocation = @{
                      artifactLocation = @{ uri = $matches[1] }
                      region = @{ startLine = [int]$matches[2] }
                    }
                  })
                  level = "warning"
                }
              }
            }
            $sarif = @{
              '$schema' = "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json"
              version = "2.1.0"
              runs = @(@{
                tool = @{
                  driver = @{
                    name = "Pascal Analyzer"
                    version = "9.0"
                    informationUri = "https://www.peganza.com"
                  }
                }
                results = $findings
              })
            }
            $sarif | ConvertTo-Json -Depth 10 | Out-File -FilePath $sarifOutputPath -Encoding UTF8
            Write-Host "Fallback SARIF report generated at $sarifOutputPath"
            return
          }

          Write-Host "Using ConvertToSARIF module..."
          Import-Module "$modulePath\ConvertToSARIF.psd1" -Force
          $lines = Get-Content $textOutputPath
          $results = foreach ($line in $lines) {
            if ($line -match "^(.+?)\((\d+)\):\s*(.+)$") {
              [PSCustomObject]@{
                RuleName = "PascalAnalyzerFinding"
                Message  = $matches[3]
                Line     = [int]$matches[2]
                Path     = $matches[1]
                Severity = "Warning"
              }
            }
          }
          $results | ConvertTo-SARIF -FilePath $sarifOutputPath
          
          # Post-process SARIF to fix tool metadata if needed
          $sarif = Get-Content $sarifOutputPath | ConvertFrom-Json
          $sarif.runs[0].tool.driver.name = "Pascal Analyzer"
          $sarif.runs[0].tool.driver.informationUri = "https://www.peganza.com"
          $sarif | ConvertTo-Json -Depth 10 | Out-File -FilePath $sarifOutputPath -Encoding UTF8
          Write-Host "SARIF tool metadata corrected."

      - name: Upload SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: pascal-analyzer-sarif
          path: MultiSubnetFailoverTest/results.sarif
