name: Delphi Code Scan
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  code-scan:
    runs-on: [self-hosted, Windows, X64, Delphi-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile with Delphi MSBuild
        shell: powershell
        run: |
          $studioPath = "C:\Program Files (x86)\Embarcadero\Studio\22.0"
          $rsvarsPath = "$studioPath\bin\rsvars.bat"
          # Find .dproj file
          $dprojFile = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter *.dproj | Select-Object -First 1
          if (-not $dprojFile) {
            Write-Host "ERROR: No .dproj file found."
            exit 1
          }
          $dprojPath = $dprojFile.FullName
          Write-Host "Found .dproj: $dprojPath"
          if (-not (Test-Path $rsvarsPath)) {
            Write-Host "ERROR: rsvars.bat not found at $rsvarsPath"
            exit 1
          }
          # Proper command line for CMD: no double-double-quotes!
          $cmd = "`"$rsvarsPath`" && msbuild `"$dprojPath`" /p:Config=Release /p:Platform=Win32"
          Write-Host "Running Delphi MSBuild with rsvars.bat..."
          cmd.exe /c $cmd
          if ($LASTEXITCODE -ne 0) {
            Write-Host "ERROR: Delphi MSBuild failed with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }
          Write-Host " Compilation completed successfully!"
          
      - name: Run Pascal Analyzer
        shell: powershell
        run: |
          $projectPath = "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\Project1.dpr"
          $palcmdPath = "C:\Program Files\Peganza\Pascal Analyzer Eval 9\palcmd.exe"
          
          # Pascal Analyzer's default output directory
          $paOutputDir = "C:\Users\$env:USERNAME\Documents\Pascal Analyzer\Projects\Output\Project1"
          $warningsFile = "$paOutputDir\Warnings.txt"
          $bindingsFile = "$paOutputDir\Bindings.txt"
          
          # Our target locations
          $targetOutputDir = "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest"
          $targetWarningsFile = "$targetOutputDir\analysis-output.txt"
      
          if (-not (Test-Path $palcmdPath)) {
            Write-Host "ERROR: palcmd.exe not found at: $palcmdPath"
            exit 1
          }
      
          # Ensure our target directory exists
          if (-not (Test-Path $targetOutputDir)) {
            New-Item -ItemType Directory -Force -Path $targetOutputDir
          }
      
          # Clean up any previous Pascal Analyzer output
          if (Test-Path $paOutputDir) {
            Write-Host "Cleaning up previous Pascal Analyzer output..."
            Remove-Item "$paOutputDir\*" -Force -ErrorAction SilentlyContinue
          }
      
          Write-Host "Project path: $projectPath"
          Write-Host "Pascal Analyzer output directory: $paOutputDir"
          Write-Host "Target output file: $targetWarningsFile"
      
          # Run Pascal Analyzer (it will use its default output location)
          Write-Host "Running Pascal Analyzer..."
          & "$palcmdPath" "$projectPath"
      
          if ($LASTEXITCODE -ne 0) {
            Write-Host "ERROR: Pascal Analyzer failed with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }
      
          Write-Host "Pascal Analyzer completed. Checking output files..."
      
          # List all files in Pascal Analyzer's output directory
          if (Test-Path $paOutputDir) {
            Write-Host "Files in Pascal Analyzer output directory:"
            Get-ChildItem $paOutputDir -ErrorAction SilentlyContinue | ForEach-Object { 
              Write-Host "  - $($_.Name) (Size: $($_.Length) bytes)"
            }
          } else {
            Write-Host "ERROR: Pascal Analyzer output directory not found at: $paOutputDir"
            exit 1
          }
      
          # Copy the warnings file to our target location
          if (Test-Path $warningsFile) {
            Copy-Item $warningsFile $targetWarningsFile
            $fileSize = (Get-Item $targetWarningsFile).Length
            Write-Host "Copied Warnings.txt to analysis-output.txt (Size: $fileSize bytes)"
            
            # Show first few lines for verification
            if ($fileSize -gt 0) {
              Write-Host "First few lines of warnings file:"
              Get-Content $targetWarningsFile -TotalCount 10 | ForEach-Object { Write-Host "  $_" }
            }
          } elseif (Test-Path $bindingsFile) {
            # Fallback to Bindings.txt if Warnings.txt doesn't exist
            Copy-Item $bindingsFile $targetWarningsFile
            Write-Host "Copied Bindings.txt to analysis-output.txt as fallback"
          } else {
            # Try to find any .txt file in the output directory
            $txtFiles = Get-ChildItem $paOutputDir -Filter "*.txt" -ErrorAction SilentlyContinue
            if ($txtFiles.Count -gt 0) {
              $firstTxtFile = $txtFiles[0]
              Copy-Item $firstTxtFile.FullName $targetWarningsFile
              Write-Host "Copied $($firstTxtFile.Name) to analysis-output.txt"
            } else {
              Write-Host "ERROR: No suitable output file found in Pascal Analyzer output directory"
              exit 1
            }
          }
      
          Write-Host "Pascal Analyzer processing completed successfully."
          
      - name: Convert Pascal Analyzer output to SARIF
        shell: powershell
        run: |
          $textOutputPath = "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\analysis-output.txt"
          $sarifOutputPath = "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\results.sarif"
      
          # Check if the text output file exists
          if (-not (Test-Path $textOutputPath)) {
            Write-Host "ERROR: Pascal Analyzer output file not found at: $textOutputPath"
            Write-Host "Available files in directory:"
            Get-ChildItem "$env:GITHUB_WORKSPACE\MultiSubnetFailoverTest\" | ForEach-Object { Write-Host "  - $($_.Name)" }
            exit 1
          }
      
          Write-Host "Converting Pascal Analyzer output to SARIF format..."
          Write-Host "Input file: $textOutputPath"
          Write-Host "Output file: $sarifOutputPath"
      
          # Read the Pascal Analyzer output
          $lines = Get-Content $textOutputPath -ErrorAction SilentlyContinue
          Write-Host "Read $($lines.Count) lines from Pascal Analyzer output"
      
          # Show first few lines for debugging
          Write-Host "First 10 lines of Pascal Analyzer output:"
          $lines | Select-Object -First 10 | ForEach-Object { Write-Host "  $_" }
      
          # Parse Pascal Analyzer output and create SARIF findings
          $findings = @()
          $lineNumber = 0
          
          foreach ($line in $lines) {
            $lineNumber++
            
            # Try multiple patterns to match Pascal Analyzer output
            $matched = $false
            
            # Pattern 1: File(line): message
            if ($line -match '^(.+?)\((\d+)\):\s*(.+)
            
      - name: Upload SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: pascal-analyzer-sarif
          path: MultiSubnetFailoverTest/results.sarif) {
              $findings += @{
                ruleId = "PascalAnalyzer.Finding"
                message = @{ text = $matches[3].Trim() }
                locations = @(@{
                  physicalLocation = @{
                    artifactLocation = @{ uri = $matches[1].Trim() }
                    region = @{ startLine = [int]$matches[2] }
                  }
                })
                level = "warning"
              }
              $matched = $true
            }
            # Pattern 2: File:line: message
            elseif ($line -match '^(.+?):(\d+):\s*(.+)
            
      - name: Upload SARIF Report2
        uses: actions/upload-artifact@v4
        with:
          name: pascal-analyzer-sarif
          path: MultiSubnetFailoverTest/results.sarif) {
              $findings += @{
                ruleId = "PascalAnalyzer.Finding"
                message = @{ text = $matches[3].Trim() }
                locations = @(@{
                  physicalLocation = @{
                    artifactLocation = @{ uri = $matches[1].Trim() }
                    region = @{ startLine = [int]$matches[2] }
                  }
                })
                level = "warning"
              }
              $matched = $true
            }
            # Pattern 3: Lines that contain "Warning", "Error", "Info" etc.
            elseif ($line -match '(warning|error|info|note)[:]\s*(.+)', 'IgnoreCase') {
              $severity = switch ($matches[1].ToLower()) {
                "error" { "error" }
                "warning" { "warning" }
                "info" { "note" }
                "note" { "note" }
                default { "warning" }
              }
              
              $findings += @{
                ruleId = "PascalAnalyzer.General"
                message = @{ text = $matches[2].Trim() }
                locations = @(@{
                  physicalLocation = @{
                    artifactLocation = @{ uri = "Project1.dpr" }
                    region = @{ startLine = 1 }
                  }
                })
                level = $severity
              }
              $matched = $true
            }
            # Pattern 4: Any line that looks like it contains a file path
            elseif ($line -match '\.pas|\.dpr|\.inc' -and $line.Trim() -ne '') {
              $findings += @{
                ruleId = "PascalAnalyzer.CodeIssue"
                message = @{ text = $line.Trim() }
                locations = @(@{
                  physicalLocation = @{
                    artifactLocation = @{ uri = "Project1.dpr" }
                    region = @{ startLine = 1 }
                  }
                })
                level = "info"
              }
              $matched = $true
            }
            
            if ($matched) {
              Write-Host "  Parsed line $lineNumber`: $line"
            }
          }
      
          Write-Host "Created $($findings.Count) SARIF findings from Pascal Analyzer output"
      
          # Create the SARIF structure
          $sarif = @{
            '$schema' = "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json"
            version = "2.1.0"
            runs = @(@{
              tool = @{
                driver = @{
                  name = "Pascal Analyzer"
                  version = "9.0"
                  informationUri = "https://www.peganza.com/products_pal.html"
                  rules = @(
                    @{
                      id = "PascalAnalyzer.Finding"
                      name = "PascalAnalyzerFinding"
                      shortDescription = @{ text = "Pascal Analyzer Code Finding" }
                      fullDescription = @{ text = "Code analysis finding from Pascal Analyzer" }
                    },
                    @{
                      id = "PascalAnalyzer.General"
                      name = "PascalAnalyzerGeneral"
                      shortDescription = @{ text = "Pascal Analyzer General Issue" }
                      fullDescription = @{ text = "General code analysis issue from Pascal Analyzer" }
                    },
                    @{
                      id = "PascalAnalyzer.CodeIssue"
                      name = "PascalAnalyzerCodeIssue"
                      shortDescription = @{ text = "Pascal Analyzer Code Issue" }
                      fullDescription = @{ text = "Code quality issue identified by Pascal Analyzer" }
                    }
                  )
                }
              }
              results = $findings
              columnKind = "utf16CodeUnits"
            })
          }
          
          # Convert to JSON and save
          $sarifJson = $sarif | ConvertTo-Json -Depth 10
          $sarifJson | Out-File -FilePath $sarifOutputPath -Encoding UTF8
          
          Write-Host "SARIF report generated successfully at: $sarifOutputPath"
          Write-Host "Total findings: $($findings.Count)"
          
          # Verify the file was created and show its size
          if (Test-Path $sarifOutputPath) {
            $fileSize = (Get-Item $sarifOutputPath).Length
            Write-Host "SARIF file size: $fileSize bytes"
            
            # Show a preview of the generated SARIF
            Write-Host "SARIF preview (first 500 characters):"
            $preview = Get-Content $sarifOutputPath -Raw
            Write-Host $preview.Substring(0, [Math]::Min(500, $preview.Length))
          } else {
            Write-Host "ERROR: Failed to create SARIF file"
            exit 1
          }
          
      - name: Upload SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: pascal-analyzer-sarif
          path: MultiSubnetFailoverTest/results.sarif
